### ISSUE TITLE
Stream API

### ISSUE THREAD

**Issue by AlphaBeth** [nymphaea-v1/Lab6#6]
https://github.com/nymphaea-v1/Lab6/blob/732303d41ea9c2d2a3536aa9f0ea076da985fe12/src/server/commands/CountByType.java#L28

**Comment by nymphaea-v1** [comment]
https://github.com/nymphaea-v1/Lab6/commit/66a66703fdb64e9f23af27cea1490283c889db58

https://github.com/nymphaea-v1/Lab6/blob/66a66703fdb64e9f23af27cea1490283c889db58/src/server/commands/CountByType.java#L26-L28
