### ISSUE TITLE
Если нет соединения с сервером, то клиент начинает бесконечно выводить сообщение об этом

### ISSUE THREAD

**Issue by AlphaBeth** [nymphaea-v1/Lab6#9]
При этом даже не реагирует на команду exit, как остановить его?

**Comment by nymphaea-v1** [comment]
Метод коннекта, предлагающий повторную попытку коннекта в случае неудачи (строки 48-50):
https://github.com/nymphaea-v1/Lab6/blob/13d78ce513245b91cca2c54519e7a85a24451f26/src/client/ServerConnector.java#L27-L53 
Соответствующие изменения в мейне:
https://github.com/nymphaea-v1/Lab6/blob/13d78ce513245b91cca2c54519e7a85a24451f26/src/client/Main.java#L23-L30
